// components/templates/EmailEditor/constants/toolboxItems.ts
export const TOOLBOX_ITEMS = [
    { id: 'text', label: 'Văn bản', icon: 'Type', cat: 'content' },
    { id: 'image', label: 'Hình ảnh', icon: 'Image', cat: 'content' },
    { id: 'button', label: 'Nút bấm', icon: 'MousePointer2', cat: 'content' },
    { id: 'check_list', label: 'Checklist', icon: 'CheckCircle', cat: 'template_tab' },
    { id: 'order_list', label: 'DS Hàng hóa', icon: 'ShoppingBag', cat: 'content' },
    { id: 'video', label: 'Video', icon: 'Video', cat: 'content' },
    { id: 'social', label: 'Mạng xã hội', icon: 'Share2', cat: 'content' },
    { id: 'quote', label: 'Trích dẫn', icon: 'Quote', cat: 'content' },
    { id: 'timeline', label: 'Timeline', icon: 'List', cat: 'content' },
    { id: 'review', label: 'Đánh giá', icon: 'Star', cat: 'content' },
    { id: 'countdown', label: 'Đếm ngược', icon: 'Clock', cat: 'template_tab' },
    { id: 'voucher', label: 'Voucher', icon: 'Ticket', cat: 'template_tab' },
    { id: 'divider', label: 'Divider', icon: 'Minus', cat: 'basic' },
    { id: 'table', label: 'Bảng', icon: 'Table2', cat: 'basic' },
    { id: 'otp', label: 'Mã OTP', icon: 'KeyRound', cat: 'template_tab' },
    { id: 'footer', label: 'Footer', icon: 'PanelBottom', cat: 'basic' },
    { id: 'header', label: 'Header', icon: 'Layout', cat: 'basic' },
    { id: 'spacer', label: 'Spacer', icon: 'Layers', cat: 'basic' },
    { id: '1', type: 'layout', layout: '1', label: '1 Cột', cat: 'layout' },
    { id: '2', type: 'layout', layout: '2', label: '2 Cột', cat: 'layout' },
    { id: '3', type: 'layout', layout: '3', label: '3 Cột', cat: 'layout' },
    { id: '4', type: 'layout', layout: '4', label: '4 Cột', cat: 'layout' },
    { id: '1-2', type: 'layout', layout: '1-2', label: 'Trái nhỏ', cat: 'layout' },
    { id: '2-1', type: 'layout', layout: '2-1', label: 'Phải nhỏ', cat: 'layout' },
    // Presets (Moved to separate tab)
    { id: 'header_gradient', label: 'Welcome Hero', icon: 'Sparkle', cat: 'template_tab' },
    { id: 'article_list', label: 'Tin Tức', icon: 'Newspaper', cat: 'template_tab' },
    { id: 'ecommerce_product', label: 'Sản Phẩm', icon: 'ShoppingBag', cat: 'template_tab' },
    { id: 'steps_flow_number', label: '3 Bước (Số)', icon: 'ListOrdered', cat: 'template_tab' },
    { id: 'steps_flow', label: '3 Bước (L/M)', icon: 'Milestone', cat: 'template_tab' },
    { id: 'double_card', label: 'Double Card', icon: 'Columns', cat: 'template_tab' },
    { id: 'review_card', label: 'Customer Review', icon: 'Star', cat: 'template_tab' },
    { id: 'feature_card', label: 'Feature Card', icon: 'Sparkles', cat: 'template_tab' },
    { id: 'download_badges', label: 'App Badges', icon: 'Download', cat: 'template_tab' },
];
