const fs = require("fs");
// Binary-level fix: read as Buffer, identify byte sequences for corrupted chars
const path = "e:/AUTOFLOW/AUTOMATION_FLOW/components/flows/modals/StepParticipantsModal.tsx";
let content = fs.readFileSync(path, "utf8");

// Regex-based replacements for remaining mojibake patterns
const regexMap = [
    // C? -> Có, Th? -> Thể, etc.  (Windows-1252 fragments)
    [/C\u00f3 l\?i x\?y ra/g, "Có lỗi xảy ra"],
    [/Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n thao t\u00e1c/g, "Không thể thực hiện thao tác"],
    [/Kh\u00f3ng/g, "Không"],
    [/th\u1ec3/g, "thể"],
    [/th\u1ef1c hi\u1ec7n/g, "thực hiện"],
    [/thao t\u00e1c/g, "thao tác"],
    // ??? question marks standing in for Vietnamese chars
    [/C\xc3\xa2 l\?i x\?y ra/g, "Có lỗi xảy ra"],
    [/Kh\xc3\xb5ng th\? th\?c hi\?n thao t\xc3\xa2c/g, "Không thể thực hiện thao tác"],
    [/Vui l\xc3\xb5ng ch\?n tag/g, "Vui lòng chọn tag"],
    [/Vui l\xc3\xb5ng ch\?n/g, "Vui lòng chọn"],
    [/lu\?t click/g, "lượt click"],
    [/d\xc3\xa2 ch\?n/g, "đã chọn"],
    [/Nh\xc3\xa2nh YES/g, "Nhánh YES"],
    [/Nh\xc3\xa2nh NO/g, "Nhánh NO"],
    // Latin extended as question marks
    [/L\?n d\?u:/g, "Lần đầu:"],
    [/S\? l\?n/g, "Số lần"],
    [/Bu\?c cu\?i c\xc3\xb5ng/g, "Bước cuối cùng"],
    [/Bu\?c cu\?i/g, "Bước cuối"],
    [/Bu\?c n\xc3\xa2y/g, "bước này"],
    [/bu\?c n\xc3\xa2y/g, "bước này"],
    [/nh\xc3\xa2nh/g, "nhánh"],
    [/Nh\xc3\xa2nh/g, "Nhánh"],
    [/V\? tr\xc3\xad b\?t d\?u/g, "Vị trí bắt đầu"],
    [/M\?c d\?nh/g, "Mặc định"],
    [/B\?t bu\?c/g, "Bắt buộc"],
    [/Lo\?i b\? T\?T C\?/g, "Loại bỏ TẤT CẢ"],
    [/Lo\?i b\?/g, "Loại bỏ"],
    [/X\xc3\xa2c nh\?n lo\?i b\?/g, "Xác nhận loại bỏ"],
    [/X\xc3\xa2c nh\?n g\?n Tag/g, "Xác nhận gắn Tag"],
    [/X\xc3\xa2c nh\?n th\xc3\xa0m v\xc3\xa0o List/g, "Xác nhận thêm vào List"],
    [/X\xc3\xa2c nh\?n d\?i Trạng thái/g, "Xác nhận đổi Trạng thái"],
    [/X\xc3\xa2c nh\?n/g, "Xác nhận"],
    [/G\?n Tag Khách hàng/g, "Gắn Tag Khách hàng"],
    [/G\?n Tag/g, "Gắn Tag"],
    [/Ch\?n Tag/g, "Chọn Tag"],
    [/Ch\?n tag mu\?n g\?n cho/g, "Chọn tag muốn gắn cho"],
    [/Ch\?n list mu\?n th\xc3\xa0m/g, "Chọn list muốn thêm"],
    [/Ch\?n Danh sách/g, "Chọn Danh sách"],
    [/Ch\?n Trạng thái/g, "Chọn Trạng thái"],
    [/Ch\?n nh\xc3\xa2nh ti\?p theo/g, "Chọn nhánh tiếp theo"],
    [/\xd0\u1ee8A CH\u1ec6 IP/g, "ĐỊA CHỈ IP"],
    [/Th\?m ngu\?i d\xc3\xb5ng v\xc3\xa0o bu\?c n\xc3\xa2y/g, "Thêm người dùng vào bước này"],
    [/S\xd4T \/ Zalo UID/g, "SĐT / Zalo UID"],
    [/M\?i d\xc3\xb5ng 1/g, "Mỗi dòng 1"],
    [/nh\?ng li\xc3\xaan h\? ch\xc3\xbca/g, "những liên hệ chưa"],
    [/h\? th\?ng/g, "hệ thống"],
    [/s\? du\?c t\? d\?ng/g, "sẽ được tự động"],
    [/t\?o m\?i/g, "tạo mới"],
    [/\xd0\?i Trạng thái li\xc3\xaan h\?/g, "Đổi Trạng thái liên hệ"],
    [/H\xc3\xa0nh d\?ng nhanh/g, "Hành động nhanh"],
    [/Th\xc3\xa0m nh\xc3\xa2n cho/g, "Thêm nhãn cho"],
    [/Th\xc3\xa0m v\xc3\xa0o List/g, "Thêm vào List"],
    [/Th\xc3\xa0m v\xc3\xa0o Danh sách/g, "Thêm vào Danh sách"],
    [/Th\xc3\xa0m v\xc3\xa0o danh sách/g, "Thêm vào danh sách"],
    [/Th\xc3\xa0m ngu\?i d\xc3\xb5ng/g, "Thêm người dùng"],
    [/L\?i th\xc3\xa0m/g, "Lỗi thêm"],
    [/Chi ti\?t l\?i:/g, "Chi tiết lỗi:"],
    [/Vui l\xc3\xb5ng nh\?p/g, "Vui lòng nhập"],
    [/\xeat nh\?t/g, "ít nhất"],
    [/li\xc3\xaan h\?/g, "liên hệ"],
    [/ngu\?i d\xc3\xb5ng/g, "người dùng"],
    [/B\?n c\xc3\xb3 ch\?c mu\?n/g, "Bạn có chắc muốn"],
    [/B\?n c\xc3\xb3 ch\?c ch\?n mu\?n/g, "Bạn có chắc chắn muốn"],
    [/n\?i dung/g, "nội dung"],
    [/mu\?n g\xc3\xb5i l\?i/g, "muốn gửi lại"],
    [/ngu\?i n\xc3\xa2y/g, "người này"],
    [/ng\xc3\xa2y/g, "ngày"],
    [/ph\xc3\xbat/g, "phút"],
    [/\xd0i\?u ki\?n d\xc3\xbang/g, "Điều kiện đúng"],
    [/\xd0i\?u ki\?n sai/g, "Điều kiện sai"],
    [/Ki\?m tra/g, "Kiểm tra"],
    [/Th\xc3\xa0m ngay/g, "Thêm ngay"],
    [/\xd0ang th\xc3\xa0m/g, "Đang thêm"],
    [/ZNS d\xc3\xa2/g, "ZNS đã"],
    [/Th\xc3\xa0m v\xc3\xa0o List/g, "Thêm vào List"],
    [/ra kh\?i flow/g, "ra khỏi flow"],
    [/\u0110\u1ecang g\u1eedi l\u1ea1i/g, "Đang gửi lại"],
    [/\u0110\u1ecang th\u00eam/g, "Đang thêm"],
    [/t\xc3\xb5ng tin/g, "thông tin"],
    [/Thời gian V\xc0O/g, "Thời gian VÀO"],
    [/ZNS d\xc2\xa2\xc3\xa0đã gửi/g, "ZNS đã gửi"],
    [/Nữu ch\?n/g, "Nếu chọn"],
    [/B\? qua logic/g, "Bỏ qua logic"],
    [/v\xc3\xa0 di th\?ng/g, "và đi thẳng"],
];

regexMap.forEach(([reg, rep]) => {
    content = content.replace(reg, rep);
});

fs.writeFileSync(path, content, "utf8");
console.log("Regex replacements done");
