const fs = require("fs");
const path = "e:/AUTOFLOW/AUTOMATION_FLOW/components/flows/modals/StepParticipantsModal.tsx";
let content = fs.readFileSync(path, "utf8");

// Map of corrupted -> correct Vietnamese
const map = [
    // High-priority UI strings per user report
    ["Tổng sốpagination.total}", "Tổng số: {pagination.total}"],
    ["Danh s\xef\xbf\xbdch t\xef\xbf\xbdi:", "Danh sách tại:"],
    
    // Corrupted chars from Mojibake (C# or windows-1252 -> utf8):
    // \u00C3\u00A0 = à, \u00C3\u00A1 = á, etc.
    
    // Specific corrupted strings found:
    ["ng\u00e2y", "ngày"],
    ["ph\u00fat", "phút"],
    ["\u0110i\u1ec1u ki\u1ec7n d\u00fang", "Điều kiện đúng"],
    ["\u0110i\u1ec1u ki\u1ec7n sai", "Điều kiện sai"],
    ["C\u00f3 l?i x\u1ea3y ra", "Có lỗi xảy ra"],
    ["C\u00e2 l?i x?y ra", "Có lỗi xảy ra"],
    ["Kh\u00f4ng th\u1ec3 th\u1ef1c hi\u1ec7n thao t\u00e1c", "Không thể thực hiện thao tác"],
    ["Kh\u00f3ng th? th?c hi?n thao t\u00e2c", "Không thể thực hiện thao tác"],
    ["Vui l\u00f2ng ch\u1ecdn tag", "Vui lòng chọn tag"],
    ["Vui l\u00f5ng ch?n tag", "Vui lòng chọn tag"],
    ["Vui l\u00f5ng ch?n danh sách", "Vui lòng chọn danh sách"],
    ["Vui l\u00f5ng ch?n Trạng thái", "Vui lòng chọn Trạng thái"],
    ["lu?t click", "lượt click"],
    ["d\u00e2 ch?n", "đã chọn"],
    ["Nh\u00e2nh YES", "Nhánh YES"],
    ["Nh\u00e2nh NO", "Nhánh NO"],
    ["\u0110i?u ki?n d\u00fang", "Điều kiện đúng"],
    ["\u0110i?u ki?n sai", "Điều kiện sai"],
    ["\u00bfangđã gửi...", "Đang gửi..."],
    ["\u00bfang th\u00e0m...", "Đang thêm..."],
    ["H\u00e0nh d?ng nhanh", "Hành động nhanh"],
    ["G?n Tag", "Gắn Tag"],
    ["Th\u00e0m nh\u00e2n cho", "Thêm nhãn cho"],
    ["Th\u00e0m v\u00e0o List", "Thêm vào List"],
    ["Th\u00e0m v\u00e0o danh sách", "Thêm vào danh sách"],
    ["\u0110?i Trạng thái", "Đổi Trạng thái"],
    ["C?p nh?t Trạng thái", "Cập nhật Trạng thái"],
    ["Lo?i b? T?T C?", "Loại bỏ TẤT CẢ"],
    ["Lo?i b?", "Loại bỏ"],
    ["Bu?c cu?i c\u00f5ng", "Bước cuối cùng"],
    ["S? l?n", "Số lần"],
    ["Thời gian V\u00c0O", "Thời gian VÀO"],
    ["\u00d0\u1ecaA CH? IP", "ĐỊA CHỈ IP"],
    ["d\u00e2 ch?n t?t c?", "đã chọn tất cả"],
    ["d\u00e2 ch?n", "đã chọn"],
    ["ngu?i n\u00e2y", "người này"],
    ["ZNS d\u00e2đã gửi", "ZNS đã gửi"],
    ["\u00b6\u00b6 khớp", "Đã khớp"],
    ["Kh\u00f5ng khớp", "Không khớp"],
    ["\u00b6Đang xử lý\u00b6", "Đang xử lý"],
    ["\u00b6Đang đợi", "Đang đợi"],
    ["L?n d?u:", "Lần đầu:"],
    ["Ki?m traĐã mới", "Kiểm tra - Làm mới"],
    ["X\u00e2c nh?n lo?i b?", "Xác nhận loại bỏ"],
    ["B?n c\u00f3 chắc muốn loại", "Bạn có chắc muốn loại"],
    ["ra kh?i flow?", "ra khỏi flow?"],
    ["Lo?i b?", "Loại bỏ"],
    ["Ch?n nh\u00e2nh ti?p theo", "Chọn nhánh tiếp theo"],
    ["Th\u00e0m ngu?i d\u00f5ng v\u00e0o bu?c n\u00e2y", "Thêm người dùng vào bước này"],
    ["S\u00d4T / Zalo UID", "SĐT / Zalo UID"],
    ["M?i d\u00f5ng 1 th\u00f5ng tin", "Mỗi dòng 1 thông tin"],
    ["nh?ng li\u00ean h? ch\u00fca c\u00f3 trong h? th?ng", "những liên hệ chưa có trong hệ thống"],
    ["s? du?c t? d?ng t?o m?i", "sẽ được tự động tạo mới"],
    ["V? tr\u00ed b?t d?u", "Vị trí bắt đầu"],
    ["M?c d?nh (Ki?m tra Logic/Random)", "Mặc định (Kiểm tra Logic/Random)"],
    ["\u00f6\u00f6 ch?n nh\u00e2nh", "Đã chọn nhánh"],
    ["B?t bu?c v\u00e0o nh\u00e2nh (B?o qua logic)", "Bắt buộc vào nhánh (Bỏ qua logic)"],
    ["Bỏ qua\u003c/b\u003e logic c?a bu?c n\u00e2y v\u00e0 di th?ng v\u00e0o nh\u00e2nh d\u00e2 ch?n", "Bỏ qua</b> logic của bước này và đi thẳng vào nhánh đã chọn"],
    ["Vui l\u00f5ng nh?p \u00ect nh?t 1 li\u00ean h?", "Vui lòng nhập ít nhất 1 liên hệ"],
    ["d\u00e2 th\u00e0m", "đã thêm"],
    ["L?i th\u00e0m Khách hàng", "Lỗi thêm Khách hàng"],
    ["Chi ti?t l?i:", "Chi tiết lỗi:"],
    ["X\u00e2c nh?n\u0064\u00e3 g\u1eedi l\u1ea1i?", "Xác nhận gửi lại?"],
    ["mu?n\u0064\u00e3 g\u1eedi l\u1ea1i", "muốn gửi lại"],
    ["bu?c n\u00e2y", "bước này"],
    ["G?n Tag Khách hàng", "Gắn Tag Khách hàng"],
    ["Ch?n tag mu?n g?n cho", "Chọn tag muốn gắn cho"],
    ["Ch?n Tag", "Chọn Tag"],
    ["X\u00e2c nh?n g?n Tag", "Xác nhận gắn Tag"],
    ["Th\u00e0m v\u00e0o Danh sách", "Thêm vào Danh sách"],
    ["Ch?n list mu?n th\u00e0m", "Chọn list muốn thêm"],
    ["Ch?n Danh sách", "Chọn Danh sách"],
    ["X\u00e2c nh?n th\u00e0m v\u00e0o List", "Xác nhận thêm vào List"],
    ["\u0110?i Trạng thái li\u00ean h?", "Đổi Trạng thái liên hệ"],
    ["Ch?n Trạng tháiĐã mới", "Chọn Trạng thái mới"],
    ["X\u00e2c nh?n d?i Trạng thái", "Xác nhận đổi Trạng thái"],
    ["\u00f6\u00f6Đã gắn tag cho", "Đã gắn tag cho"],
    ["C\u00f5 l?i x?y ra", "Có lỗi xảy ra"],
    ["Kh\u00f5ng th? th?c hi\u00ebn thao t\u00e2c", "Không thể thực hiện thao tác"],
    ["\u00f6\u00f6 th\u00e0m", "Đã thêm"],
    ["v\u00e0o danh sách", "vào danh sách"],
    ["\u00f6\u00f6 c?p nh?t Trạng thái cho", "Đã cập nhật Trạng thái cho"],
    ["\u00f6\u00f6 lo?i", "Đã loại"],
    ["ra kh?i flow", "ra khỏi flow"],
    ["đ\u00e3 g\u1eedi l\u1ea1i th\u00e0nh c\u00f5ng", "đã gửi lại thành công"],
    ["Còn ${days} ng\u00e2y", "Còn ${days} ngày"],
    ["Còn ${minutes} ph\u00fat", "Còn ${minutes} phút"],
    ["\u00d0\u1ee8A CH\u1ec6 IP", "ĐỊA CHỈ IP"],
    ["Thời gian V\u00c0O", "Thời gian VÀO"],
    ["Nữu ch?n nhánh cụ thể", "Nếu chọn nhánh cụ thể"],
    ["S\u00d4T", "SĐT"],
    ["\u00b6\u00b6 lo?i", "Đã loại"],
    ["\u00b6\u00b6 th\u00e0m", "Đã thêm"],
    ["\u00b6\u00b6 gắn", "Đã gắn"],
    ["\u00b6\u00b6 c?p", "Đã cập"],
    ["B??c cu?i", "Bước cuối"],
];

map.forEach(([from, to]) => {
    try {
        content = content.split(from).join(to);
    } catch(e) {}
});

fs.writeFileSync(path, content, "utf8");
console.log("Done basic replacements");
