-- ============================================================
-- sql_fix.sql — Autoflow Schema Migration Patches
-- Run all statements in sequence. Safe to re-run (IF NOT EXISTS / IGNORE guards).
-- Generated by audit Phase 33–onwards
-- ============================================================

-- [P34-A3] web_properties now requires workspace_id column.
-- If the column doesn't already exist, add it.
ALTER TABLE `web_properties`
    ADD COLUMN IF NOT EXISTS `workspace_id` INT UNSIGNED NOT NULL DEFAULT 1
        COMMENT 'Workspace isolation — added P34' AFTER `id`;

-- Backfill existing rows to workspace 1 (root) if NULL
UPDATE `web_properties` SET `workspace_id` = 1 WHERE `workspace_id` IS NULL OR `workspace_id` = 0;

-- Add index for workspace-scoped list queries
ALTER TABLE `web_properties`
    ADD INDEX IF NOT EXISTS `idx_prop_workspace` (`workspace_id`);

-- [P35-T1] Backfill subscribers auto-created by web tracking with NULL workspace_id.
-- These were created by track.php's identify event handler before the workspace_id fix.
-- We assign them to workspace 1 (root) as a safe default.
-- After running this, verify by: SELECT id, email FROM subscribers WHERE workspace_id IS NULL;
UPDATE `subscribers` s
JOIN `web_properties` wp ON wp.id = s.property_id
SET s.workspace_id = wp.workspace_id
WHERE s.workspace_id IS NULL AND s.source = 'website_tracking' AND s.property_id IS NOT NULL;

-- Any remaining NULL workspace_id subscribers (no property_id linkage) → workspace 1
UPDATE `subscribers` SET `workspace_id` = 1 WHERE `workspace_id` IS NULL;

-- ============================================================
-- ADD MORE PATCHES BELOW AS AUDIT CONTINUES
-- ============================================================

-- ============================================================
-- PHASE 39 — Performance Index Additions
-- Generated by audit Phase 39 (2026-04-18)
-- All are IF NOT EXISTS safe to re-run.
-- ============================================================

-- [P39-IDX1] subscriber_activity: Campaign + Type composite
-- Used heavily in: worker_campaign.php NOT EXISTS subquery, campaign reports
-- Pattern: WHERE campaign_id = ? AND type IN ('receive_email', ...)
ALTER TABLE `subscriber_activity`
    ADD INDEX IF NOT EXISTS `idx_sa_campaign_type` (`campaign_id`, `type`);

-- [P39-IDX2] subscriber_activity: Subscriber + Type + CreatedAt
-- Used in: flow condition checks (opened_email, clicked_link within N days)
-- Pattern: WHERE subscriber_id = ? AND type = ? AND created_at >= ?
ALTER TABLE `subscriber_activity`
    ADD INDEX IF NOT EXISTS `idx_sa_sub_type_date` (`subscriber_id`, `type`, `created_at`);

-- [P39-IDX3] subscriber_activity: Flow + Type 
-- Used in: flow analytics (opens, clicks, unsubscribes per flow)
-- Pattern: WHERE flow_id = ? AND type = 'open_email'
ALTER TABLE `subscriber_activity`
    ADD INDEX IF NOT EXISTS `idx_sa_flow_type` (`flow_id`, `type`);

-- [P39-IDX4] subscriber_flow_states: Flow + Status + ScheduledAt
-- Used in: worker_flow.php, worker_priority.php — batch poll for due items
-- Pattern: WHERE flow_id IN (...) AND status = 'waiting' AND scheduled_at <= NOW()
ALTER TABLE `subscriber_flow_states`
    ADD INDEX IF NOT EXISTS `idx_sfs_flow_status_sched` (`flow_id`, `status`, `scheduled_at`);

-- [P39-IDX5] subscriber_flow_states: Subscriber + Flow (unique lookup)
-- Used in: campaign worker enrollment checks
-- Pattern: WHERE subscriber_id = ? AND flow_id = ?
ALTER TABLE `subscriber_flow_states`
    ADD INDEX IF NOT EXISTS `idx_sfs_sub_flow` (`subscriber_id`, `flow_id`);

-- [P39-IDX6] zalo_automation_scenarios: OA Config + Status + Type
-- Used in: webhook.php, zalo_inbound_processor.php (every inbound Zalo message)
-- Pattern: WHERE oa_config_id = ? AND status = 'active' AND type IN (...)
ALTER TABLE `zalo_automation_scenarios`
    ADD INDEX IF NOT EXISTS `idx_zas_config_status_type` (`oa_config_id`, `status`, `type`);

-- [P39-IDX7] meta_automation_scenarios: Config + Status + Type
-- Used in: meta_webhook.php, meta_inbound_processor.php (every Meta message)
-- Pattern: WHERE meta_config_id = ? AND status = 'active' AND type IN (...)
ALTER TABLE `meta_automation_scenarios`
    ADD INDEX IF NOT EXISTS `idx_mas_config_status_type` (`meta_config_id`, `status`, `type`);

-- [P39-IDX8] subscribers: Workspace + Status
-- Used in: worker_campaign.php, bulk audience queries
-- Pattern: WHERE workspace_id = ? AND status IN ('active', 'lead', 'customer')
ALTER TABLE `subscribers`
    ADD INDEX IF NOT EXISTS `idx_sub_workspace_status` (`workspace_id`, `status`);

-- [P39-IDX9] subscribers: Email lookup (already likely exists but ensure)
-- Used in: track.php identify, all subscription forms
-- Pattern: WHERE email = ?
ALTER TABLE `subscribers`
    ADD INDEX IF NOT EXISTS `idx_sub_email` (`email`);

-- [P39-IDX10] web_visitors: Property + Subscriber
-- Used in: track.php identify link, live visitors query
-- Pattern: WHERE property_id = ? AND subscriber_id = ?
ALTER TABLE `web_visitors`
    ADD INDEX IF NOT EXISTS `idx_wv_prop_sub` (`property_id`, `subscriber_id`);

-- [P39-IDX11] web_sessions: Property + LastActiveAt (live visitor queries)
-- Used in: web_tracking.php live_visitors, track.php session lookup
-- Pattern: WHERE property_id = ? AND last_active_at >= DATE_SUB(NOW(), INTERVAL 30 MINUTE)
ALTER TABLE `web_sessions`
    ADD INDEX IF NOT EXISTS `idx_ws_prop_active` (`property_id`, `last_active_at`);

-- [P39-IDX12] web_sessions: Visitor + Property (session lookup per visitor)
-- Used in: track.php 30-min session window lookup
-- Pattern: WHERE visitor_id = ? AND property_id = ? AND last_active_at > DATE_SUB(NOW(), INTERVAL 30 MINUTE)
ALTER TABLE `web_sessions`
    ADD INDEX IF NOT EXISTS `idx_ws_visitor_prop` (`visitor_id`, `property_id`, `last_active_at`);

-- [P39-IDX13] mail_delivery_logs: Status + SentAt (SES quota dashboard)
-- Used in: check_ses_quota.php 24h stats
-- Pattern: WHERE status = 'failed' AND sent_at >= DATE_SUB(NOW(), INTERVAL 24 HOUR)
ALTER TABLE `mail_delivery_logs`
    ADD INDEX IF NOT EXISTS `idx_mdl_status_sent` (`status`, `sent_at`);

-- [P39-IDX14] campaigns: Status + ScheduledAt (worker_campaign.php dispatch)
-- Used in: worker_campaign.php next-campaign poll
-- Pattern: WHERE status IN ('scheduled','sending') AND scheduled_at <= NOW()
ALTER TABLE `campaigns`
    ADD INDEX IF NOT EXISTS `idx_camp_status_sched` (`status`, `scheduled_at`);

-- [P39-IDX15] flows: Workspace + Status (worker_flow active flow lookup)
-- Pattern: WHERE workspace_id = ? AND status = 'active'
ALTER TABLE `flows`
    ADD INDEX IF NOT EXISTS `idx_flows_workspace_status` (`workspace_id`, `status`);

-- ============================================================
-- PHASE 40 — AI Space & Security Schema Patches
-- Generated by Final Audit (2026-04-18)
-- ============================================================

-- [P40-IDX1] ai_org_conversations: User + Status + Created (conversation list by user)
-- Used in: get_conversation_history (frequent admin inbox load)
-- Pattern: WHERE user_id = ? AND status != 'deleted' ORDER BY created_at DESC LIMIT 50
ALTER TABLE `ai_org_conversations`
    ADD INDEX IF NOT EXISTS `idx_aoc_uid_status_date` (`user_id`, `status`, `created_at`);

-- [P40-IDX2] ai_org_conversations: property_id + status (filter by chatbot across all convs)
-- Pattern: WHERE property_id = ? AND status != 'deleted'
ALTER TABLE `ai_org_conversations`
    ADD INDEX IF NOT EXISTS `idx_aoc_prop_status` (`property_id`, `status`);

-- [P40-IDX3] ai_org_messages: conversation_id + created_at (message history load)
-- Used in: every chat history fetch
-- Pattern: WHERE conversation_id = ? ORDER BY created_at ASC
ALTER TABLE `ai_org_messages`
    ADD INDEX IF NOT EXISTS `idx_aom_conv_date` (`conversation_id`, `created_at`);

-- [P40-IDX4] ai_workspace_files: conversation_id (file listing per session)
-- Used in: workspace_list, workspace_delete (every workspace operation)
-- Pattern: WHERE conversation_id = ? OR conversation_id = ?
ALTER TABLE `ai_workspace_files`
    ADD INDEX IF NOT EXISTS `idx_awf_conversation` (`conversation_id`);

-- [P40-IDX5] ai_training_docs: property_id + status + is_active
-- Used in: list_docs, worker train_pending (hot path)
-- Pattern: WHERE property_id = ? AND is_active = 1 AND status IN ('pending', 'error')
ALTER TABLE `ai_training_docs`
    ADD INDEX IF NOT EXISTS `idx_atd_prop_status_active` (`property_id`, `status`, `is_active`);

-- [P40-IDX6] ai_training_chunks: property_id (RAG search + BM25 scoring)
-- Used in: every AI chat query similarity search (highest traffic)
-- Pattern: WHERE property_id = ? ORDER BY ... (vector search)
ALTER TABLE `ai_training_chunks`
    ADD INDEX IF NOT EXISTS `idx_atc_property` (`property_id`);

-- [P40-IDX7] ai_org_users: admin_id + status (org user listing)
-- Used in: ai_org_users.php list action (every org management page load)
-- Pattern: WHERE admin_id = ? OR id = ? ORDER BY created_at DESC
ALTER TABLE `ai_org_users`
    ADD INDEX IF NOT EXISTS `idx_aou_admin_status` (`admin_id`, `status`);

-- [P40-IDX8] ai_org_access_tokens: user_id + is_active + expires_at (token auth)
-- Used in: requireAISpaceAuth() Bearer token validation
-- Pattern: WHERE token = ? AND expires_at > NOW() AND is_active = 1
ALTER TABLE `ai_org_access_tokens`
    ADD INDEX IF NOT EXISTS `idx_aoat_user_active_exp` (`user_id`, `is_active`, `expires_at`);

-- [P40-IDX9] global_assets: conversation_id + is_deleted (workspace asset list)
-- Pattern: WHERE (conversation_id = ? OR conversation_id = ?) AND is_deleted = 0
ALTER TABLE `global_assets`
    ADD INDEX IF NOT EXISTS `idx_ga_conv_deleted` (`conversation_id`, `is_deleted`);

-- [P40-S1] SECURITY: Ensure ai_org_users has updated_at column
-- Needed for row-level audit without full table scan in large orgs
ALTER TABLE `ai_org_users`
    ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `created_at`;

-- [P40-S2] SECURITY: Ensure ai_feedback table exists (created lazily in code,
-- but explicit schema definition ensures FK-readiness and correct collation)
CREATE TABLE IF NOT EXISTS `ai_feedback` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `org_user_id` INT NULL,
    `category_id` VARCHAR(100) NULL,
    `property_id` VARCHAR(100) NULL,
    `conversation_id` VARCHAR(255) NULL,
    `type` ENUM('bug','suggestion','praise','other') NOT NULL DEFAULT 'other',
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `screenshot_url` VARCHAR(1000) NULL,
    `page_url` VARCHAR(1000) NULL,
    `user_agent` VARCHAR(512) NULL,
    `status` ENUM('new','in_review','resolved','closed') NOT NULL DEFAULT 'new',
    `admin_note` TEXT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_aif_status` (`status`),
    INDEX `idx_aif_type` (`type`),
    INDEX `idx_aif_org_user` (`org_user_id`),
    INDEX `idx_aif_property` (`property_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- END PHASE 40 PATCHES
-- ============================================================

-- ============================================================
-- PHASE 41 — Flow List Performance & Additional Hardening
-- Generated by audit Phase 41 (2026-04-18)
-- ============================================================

-- [P41-IDX1] flows: workspace_id + created_at (list view ORDER BY)
-- PERF-F1 fix: COUNT + paginated SELECT both scan workspace scope then order by date
-- Pattern: WHERE workspace_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
ALTER TABLE `flows`
    ADD INDEX IF NOT EXISTS `idx_flows_workspace_created` (`workspace_id`, `created_at`);

-- [P41-IDX2] flows: workspace_id + status + created_at (filtered list)
-- PERF-F2 fix: status filter now passed in GET ?status= for frontend filters
-- Pattern: WHERE workspace_id = ? AND status = ? ORDER BY created_at DESC
ALTER TABLE `flows`
    ADD INDEX IF NOT EXISTS `idx_flows_workspace_status_created` (`workspace_id`, `status`, `created_at`);

-- [P41-IDX3] subscriber_activity: reference_id + type (step analytics join)
-- Used in: flows.php analytics — GROUP BY reference_id, type (per-step open/click/fail rates)
-- Pattern: WHERE flow_id = ? GROUP BY reference_id, type
ALTER TABLE `subscriber_activity`
    ADD INDEX IF NOT EXISTS `idx_sa_refid_type` (`reference_id`, `type`);

-- [P41-IDX4] subscriber_flow_states: flow_id + step_id + status (bulk-next-step, step error view)
-- Used in: flows.php bulk-next-step, step-errors, step-unsubscribes
-- Pattern: WHERE flow_id = ? AND step_id = ? AND status IN ('waiting', 'failed')
ALTER TABLE `subscriber_flow_states`
    ADD INDEX IF NOT EXISTS `idx_sfs_flow_step_status` (`flow_id`, `step_id`, `status`);

-- [P41-IDX5] zalo_delivery_logs: flow_id + step_id (ZNS delivery report)
-- Used in: flows.php zns-delivery route
-- Pattern: WHERE flow_id = ? AND step_id = ? ORDER BY created_at DESC
ALTER TABLE `zalo_delivery_logs`
    ADD INDEX IF NOT EXISTS `idx_zdl_flow_step` (`flow_id`, `step_id`);

-- [P41-IDX6] subscriber_lists: list_id + subscriber_id (bulk add/remove)
-- Used in: bulk_operations.php, subscribers.php batch add-to-list
-- Pattern: WHERE list_id = ? (already covered by assumed PK, but add if missing)
ALTER TABLE `subscriber_lists`
    ADD INDEX IF NOT EXISTS `idx_sl_list_sub` (`list_id`, `subscriber_id`);

-- [P41-S1] SECURITY: subscribers table — ensure lead_score column indexed for score-sort
-- Used in: subscribers.php ORDER BY s.lead_score DESC (sort by score filter)
ALTER TABLE `subscribers`
    ADD INDEX IF NOT EXISTS `idx_sub_workspace_score` (`workspace_id`, `lead_score`);

-- [P41-S2] PERF: subscriber_activity: flow_id + type + subscriber_id (condition check cache-miss path)
-- Used in: FlowExecutor.php condition step DB fallback (cache miss)
-- Pattern: WHERE subscriber_id = ? AND type IN (...) AND flow_id = ?
ALTER TABLE `subscriber_activity`
    ADD INDEX IF NOT EXISTS `idx_sa_sub_flow_type` (`subscriber_id`, `flow_id`, `type`);

-- [P41-CLEANUP] Log file rotation reminder (manual step, no SQL needed):
-- The following files have grown very large and should be truncated in production:
--   api/error_log           (24MB) — truncate with: > api/error_log
--   api/worker_flow.log     (21MB) — truncate with: > api/worker_flow.log
--   api/worker_campaign.log (8.8MB) — truncate with: > api/worker_campaign.log
--   api/worker_sync.log     (3MB)  — truncate with: > api/worker_sync.log
-- Add logrotate config to prevent future accumulation.

-- ============================================================
-- END PHASE 41 PATCHES
-- ============================================================
