-- ============================================================
-- sql_fix.sql — MIGRATION ARCHIVE
-- Last run : 2026-04-19 15:59 (UTC+7)
-- Status   : ALL 86 STATEMENTS APPLIED SUCCESSFULLY (0 errors)
-- ============================================================
-- This file has been cleared after successful migration.
-- All patches are now reflected in database.sql (canonical schema).
-- Future schema changes should be made directly to database.sql
-- and run via run_migration.php with appropriate ALTER statements.
-- ============================================================